# Generated by Django 4.0.3 on 2022-03-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_usuario', '0002_alter_estudiantes_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='ubicacion',
            field=models.PositiveBigIntegerField(blank=True, db_column='Ubicacion', null=True),
        ),
    ]
