# Generated by Django 4.0.3 on 2022-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cambioapart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(db_column='Nombres', max_length=100, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=100, verbose_name='Apellidos')),
                ('usuario', models.CharField(db_column='Usuario', max_length=100, verbose_name='usuario')),
                ('ubicacion', models.PositiveSmallIntegerField(db_column='Ubicacion')),
                ('motivo', models.TextField(db_column='motivo')),
            ],
            options={
                'verbose_name': 'Solicitud Cambio de Apartamento',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'Solicitudes',
            },
        ),
    ]
