# Generated by Django 4.0.3 on 2022-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('date', models.DateField()),
                ('edif', models.PositiveSmallIntegerField(verbose_name='Edificio')),
                ('paso', models.PositiveSmallIntegerField(verbose_name='Paso')),
                ('apto', models.PositiveSmallIntegerField(verbose_name='Apto')),
                ('Evaluacion', models.TextField(blank=True, choices=[('Bien', 'Bien'), ('Regular', 'Regular'), ('Mal', 'Mal')], null=True, verbose_name='Eval')),
            ],
            options={
                'verbose_name': 'Cuarteleria',
                'verbose_name_plural': 'Cuartelerias',
                'db_table': 'cuarteleria',
                'ordering': ['id'],
            },
        ),
    ]
