# Generated by Django 4.0.3 on 2022-03-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_cuart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuart',
            name='usuario',
            field=models.CharField(db_column='Usuario', default=0, max_length=100, verbose_name='usuario'),
        ),
    ]
